### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Rexxah** [filippofinke/mood-meter#1]
Hello, I am very fascinated with your project because so far only you have provided the code for this topic. I have a problem because I would like to implement this program on my wordpress website, but I do not know how to do it, could you help me please? I need this for me and my girlfriend I will be very grateful (I am willing to pay for your help). Take care and please tell me back asap.

**Comment by filippofinke** [comment]
Hello, thank you for reaching out!

This project uses NodeJS, I don't think that it's an easy task to integrate it with your WordPress website. 

You should host it elsewhere and then integrate it (maybe using an iframe(?)).

**Comment by Rexxah** [comment]
Thank you for fast response!
I have some experience on hosting apps on heroku (I hosted there some Discord bots), but i dont have any idea how to deploy this project on heroku node worker doesnt seems to work, one more question how can i set up webhook in project i tried to use webhook from discord with some custom code but it didnt work.

**Comment by filippofinke** [comment]
Currently the webhook supports only IFTTT.

Never used heroku, but maybe this could help: https://devcenter.heroku.com/articles/getting-started-with-nodejs

**Comment by anjannair** [comment]
@Rexxah Do you still require help?
@filippofinke Should I put in a PR for hosting with Heroku?

**Comment by filippofinke** [comment]
> @Rexxah Do you still require help? @filippofinke Should I put in a PR for hosting with Heroku?

If you have time yes, contributions are always welcome!

**Comment by Rexxah** [comment]
> @Rexxah Do you still require help?
> 
> @filippofinke Should I put in a PR for hosting with Heroku?

No thank you i handle that and created some new features to app.

**Comment by anjannair** [comment]
> > @Rexxah Do you still require help?
> > 
> > @filippofinke Should I put in a PR for hosting with Heroku?
> 
> No thank you i handle that and created some new features to app. 

What??? So you aren't going to accept my PR?
